// frontend/src/components/Header.jsx
import React from 'react';
import { RefreshCw, CheckCircle2, AlertTriangle, Video } from 'lucide-react';

export default function Header({
  isConnected = false,
  isRefreshing = false,
  lastUpdated = new Date(),
  openAlertsCount = 0,
  refreshIntervalSec = 3,
  selectedTimeRange = 'all',
  selectedZone = '',
  onTimeRangeChange,
  onZoneChange,
  onRefreshIntervalChange,
  onRefresh,
}) {
  const formattedTime = lastUpdated
    ? new Date(lastUpdated).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })
    : '--:--:--';

  const hasIssues = openAlertsCount > 0;

  return (
    <header style={styles.header}>
      {/* Left: Store Status Summary */}
      <div style={styles.leftSection}>
        <div style={styles.storeTag}>
          <span style={styles.storeName}>Main Store</span>
          <span style={styles.storeLocation}>Ground Floor</span>
        </div>

        {/* Store Health Status Pill */}
        <div
          style={{
            ...styles.statusPill,
            backgroundColor: !isConnected
              ? 'var(--status-danger-bg)'
              : hasIssues
              ? 'var(--status-warning-bg)'
              : 'var(--status-success-bg)',
            borderColor: !isConnected
              ? 'var(--status-danger-border)'
              : hasIssues
              ? 'var(--status-warning-border)'
              : 'var(--status-success-border)',
            color: !isConnected
              ? 'var(--status-danger-text)'
              : hasIssues
              ? 'var(--status-warning-text)'
              : 'var(--status-success-text)',
          }}
        >
          {!isConnected ? (
            <>
              <AlertTriangle size={14} />
              <span>Camera Node Offline</span>
            </>
          ) : hasIssues ? (
            <>
              <AlertTriangle size={14} />
              <span>{openAlertsCount} Alerts Needing Attention</span>
            </>
          ) : (
            <>
              <CheckCircle2 size={14} />
              <span>Store Operating Normally</span>
            </>
          )}
        </div>
      </div>

      {/* Right: Store Manager Filters & Refresh */}
      <div style={styles.rightSection}>
        {/* Time Window */}
        <select
          value={selectedTimeRange}
          onChange={(e) => onTimeRangeChange && onTimeRangeChange(e.target.value)}
          style={styles.select}
          aria-label="Select time range"
        >
          <option value="all">Today (All Data)</option>
          <option value="1h">Last 1 Hour</option>
          <option value="6h">Last 6 Hours</option>
          <option value="24h">Last 24 Hours</option>
        </select>

        {/* Zone Selector */}
        <select
          value={selectedZone}
          onChange={(e) => onZoneChange && onZoneChange(e.target.value)}
          style={styles.select}
          aria-label="Filter by store area"
        >
          <option value="">All Store Areas</option>
          <option value="zone_entrance">Entrance</option>
          <option value="zone_checkout">Checkout Counters</option>
          <option value="zone_aisle_1">Grocery Aisle</option>
          <option value="zone_aisle_2">Snacks Aisle</option>
        </select>

        {/* Auto Refresh Frequency */}
        <select
          value={refreshIntervalSec}
          onChange={(e) => onRefreshIntervalChange && onRefreshIntervalChange(Number(e.target.value))}
          style={styles.select}
          aria-label="Auto-update frequency"
        >
          <option value={2}>Live (2s)</option>
          <option value={3}>Normal (3s)</option>
          <option value={5}>Relaxed (5s)</option>
          <option value={10}>Slow (10s)</option>
        </select>

        {/* Refresh Sync Button */}
        <button
          onClick={onRefresh}
          disabled={isRefreshing}
          style={styles.refreshBtn}
          title={`Last synced at ${formattedTime}`}
          aria-label="Sync store data now"
        >
          <RefreshCw
            size={13}
            style={{
              animation: isRefreshing ? 'spin 1s linear infinite' : 'none',
            }}
          />
          <span>{isRefreshing ? 'Syncing...' : 'Sync'}</span>
        </button>
      </div>

      <style>{`
        @keyframes spin {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
      `}</style>
    </header>
  );
}

const styles = {
  header: {
    height: 'var(--header-height)',
    backgroundColor: 'var(--bg-surface)',
    borderBottom: '1px solid var(--border-subtle)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 1.5rem',
    flexShrink: 0,
    gap: '1rem',
  },
  leftSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  storeTag: {
    display: 'flex',
    flexDirection: 'column',
    lineHeight: 1.2,
  },
  storeName: {
    fontSize: '0.875rem',
    fontWeight: 700,
    color: 'var(--text-main)',
  },
  storeLocation: {
    fontSize: '0.7rem',
    color: 'var(--text-subtle)',
  },
  statusPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.4rem',
    padding: '0.25rem 0.65rem',
    borderRadius: '9999px',
    border: '1px solid transparent',
    fontSize: '0.775rem',
    fontWeight: 600,
  },
  rightSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  select: {
    padding: '0.35rem 0.6rem',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--border-subtle)',
    backgroundColor: 'var(--bg-surface)',
    color: 'var(--text-main)',
    fontSize: '0.775rem',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'border-color 0.15s ease',
  },
  refreshBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.35rem',
    padding: '0.35rem 0.7rem',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--border-subtle)',
    backgroundColor: 'var(--bg-surface)',
    color: 'var(--text-main)',
    fontSize: '0.775rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'background-color 0.15s ease, border-color 0.15s ease',
  },
};

// frontend/src/components/Header.svelte
<script>
  export let isConnected = true;
  export let lastUpdated = new Date();
  export let isRefreshing = false;
  export let autoRefresh = true;
  export let refreshInterval = 3;
  export let selectedTimeRange = 'all';
  export let selectedZone = '';
  export let debugMode = false;
  export let onRefresh = () => {};
  export let onToggleDebug = () => {};

  function formatTime(date) {
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
  }
</script>

<header class="header">
  <div class="brand">
    <div class="brand-icon">
      <svg viewBox="0 0 24 24" width="22" height="22" stroke="currentColor" stroke-width="2" fill="none">
        <path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"/>
        <line x1="3" y1="6" x2="21" y2="6"/>
        <path d="M16 10a4 4 0 0 1-8 0"/>
      </svg>
    </div>
    <div class="titles">
      <div class="title-row">
        <h1>Intelligent Retail Analytics</h1>
        <span class="badge edge-badge">Edge AI • SIH26179</span>
        {#if debugMode}
          <span class="badge debug-badge">Debug Active</span>
        {/if}
      </div>
      <p class="subtitle">On-device customer traffic, checkout queues & shelf inventory intelligence</p>
    </div>
  </div>

  <div class="controls">
    <div class="filter-group">
      <label for="time-range">Range</label>
      <select id="time-range" bind:value={selectedTimeRange} on:change={onRefresh}>
        <option value="all">All Time</option>
        <option value="1h">Last 1 Hour</option>
        <option value="6h">Last 6 Hours</option>
        <option value="24h">Last 24 Hours</option>
      </select>
    </div>

    <div class="filter-group">
      <label for="zone-filter">Zone</label>
      <input 
        id="zone-filter" 
        type="text" 
        placeholder="All Zones..." 
        bind:value={selectedZone} 
        on:input={onRefresh}
      />
    </div>

    <div class="status-indicator" title="Edge server connectivity status">
      <span class="status-dot" class:connected={isConnected}></span>
      <span class="status-text">{isConnected ? 'Edge Connected' : 'Connecting...'}</span>
      <span class="timestamp">{formatTime(lastUpdated)}</span>
    </div>

    <button 
      type="button"
      class="debug-toggle-btn" 
      class:active={debugMode} 
      on:click={onToggleDebug}
      title="Toggle Debug & .env Editor"
    >
      <svg viewBox="0 0 24 24" width="14" height="14" stroke="currentColor" stroke-width="2" fill="none">
        <path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/>
      </svg>
      <span>{debugMode ? 'Debug ON' : 'Debug'}</span>
    </button>

    <div class="refresh-controls">
      <label class="auto-refresh-toggle" title="Automatic polling toggle">
        <input type="checkbox" bind:checked={autoRefresh} />
        <span>Auto ({refreshInterval}s)</span>
      </label>
      <button 
        type="button"
        class="refresh-btn" 
        class:spinning={isRefreshing} 
        on:click={onRefresh}
        title="Refresh data now"
        aria-label="Refresh data"
      >
        <svg viewBox="0 0 24 24" width="15" height="15" stroke="currentColor" stroke-width="2" fill="none">
          <path d="M21.5 2v6h-6M21.34 15.57a10 10 0 1 1-.57-8.38l5.67-5.67"/>
        </svg>
      </button>
    </div>
  </div>
</header>

<style>
  .header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1rem 2rem;
    background: var(--bg-secondary);
    border-bottom: 1px solid var(--border-color);
    position: sticky;
    top: 0;
    z-index: 50;
    gap: 1.5rem;
    flex-wrap: wrap;
    box-shadow: var(--shadow-sm);
  }

  .brand {
    display: flex;
    align-items: center;
    gap: 0.85rem;
  }

  .brand-icon {
    width: 40px;
    height: 40px;
    background: var(--accent-blue-light);
    color: var(--accent-blue);
    border: 1px solid #bfdbfe;
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: var(--radius-md);
  }

  .titles h1 {
    font-size: 1.15rem;
    font-weight: 700;
    color: var(--text-primary);
    letter-spacing: -0.02em;
  }

  .title-row {
    display: flex;
    align-items: center;
    gap: 0.6rem;
  }

  .badge {
    font-size: 0.68rem;
    font-family: var(--font-mono);
    padding: 0.12rem 0.45rem;
    border-radius: var(--radius-sm);
    font-weight: 600;
  }

  .edge-badge {
    background: var(--accent-green-light);
    color: var(--accent-green);
    border: 1px solid #a7f3d0;
  }

  .debug-badge {
    background: var(--accent-purple-light);
    color: var(--accent-purple);
    border: 1px solid #ddd6fe;
  }

  .subtitle {
    font-size: 0.78rem;
    color: var(--text-muted);
  }

  .controls {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    flex-wrap: wrap;
  }

  .filter-group {
    display: flex;
    align-items: center;
    gap: 0.4rem;
    background: var(--bg-primary);
    padding: 0.35rem 0.65rem;
    border-radius: var(--radius-sm);
    border: 1px solid var(--border-color);
    font-size: 0.8rem;
  }

  .filter-group label {
    color: var(--text-muted);
    font-weight: 500;
  }

  .filter-group select, .filter-group input {
    background: transparent;
    color: var(--text-primary);
    border: none;
    outline: none;
    font-size: 0.8rem;
  }

  .filter-group input {
    width: 90px;
  }

  .filter-group select option {
    background: #ffffff;
    color: var(--text-primary);
  }

  .status-indicator {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    background: var(--bg-primary);
    padding: 0.35rem 0.75rem;
    border-radius: var(--radius-sm);
    border: 1px solid var(--border-color);
    font-size: 0.8rem;
  }

  .status-dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background: var(--accent-red);
    transition: background 0.2s ease;
  }

  .status-dot.connected {
    background: var(--accent-green);
  }

  .status-text {
    font-weight: 500;
    color: var(--text-secondary);
  }

  .timestamp {
    color: var(--text-muted);
    font-family: var(--font-mono);
    font-size: 0.75rem;
    margin-left: 0.2rem;
  }

  .debug-toggle-btn {
    display: inline-flex;
    align-items: center;
    gap: 0.35rem;
    padding: 0.35rem 0.75rem;
    font-size: 0.78rem;
    font-weight: 600;
    background: #ffffff;
    color: var(--text-secondary);
    border: 1px solid var(--border-color);
    border-radius: var(--radius-sm);
    transition: all 0.15s ease;
  }

  .debug-toggle-btn:hover {
    color: var(--text-primary);
    border-color: #cbd5e1;
  }

  .debug-toggle-btn.active {
    background: var(--accent-purple-light);
    color: var(--accent-purple);
    border-color: #ddd6fe;
  }

  .refresh-controls {
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }

  .auto-refresh-toggle {
    display: flex;
    align-items: center;
    gap: 0.35rem;
    font-size: 0.75rem;
    color: var(--text-secondary);
    cursor: pointer;
    user-select: none;
  }

  .auto-refresh-toggle input {
    accent-color: var(--accent-blue);
    cursor: pointer;
  }

  .refresh-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 32px;
    height: 32px;
    background: #ffffff;
    color: var(--text-secondary);
    border-radius: var(--radius-sm);
    border: 1px solid var(--border-color);
    transition: all 0.15s ease;
  }

  .refresh-btn:hover {
    color: var(--accent-blue);
    border-color: #bfdbfe;
    background: var(--accent-blue-light);
  }

  .spinning svg {
    animation: spin 0.8s linear infinite;
  }

  @keyframes spin {
    100% { transform: rotate(360deg); }
  }
</style>
